name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:

env:
  APP_NAME: easymytrip
  VERSION: 1.1.${{ github.run_number }}

  IMAGE_TAG: ${{ github.run_number }}

  IMAGE_LOCAL: easymytrip:${{ github.run_number }}
  IMAGE_LOCAL_LATEST: easymytrip:latest

  IMAGE_DOCKERHUB: satyam88/easymytrip:${{ github.run_number }}
  IMAGE_DOCKERHUB_LATEST: satyam88/easymytrip:latest

  IMAGE_ECR: 445842764710.dkr.ecr.ap-south-1.amazonaws.com/easymytrip:${{ github.run_number }}
  IMAGE_ECR_LATEST: 445842764710.dkr.ecr.ap-south-1.amazonaws.com/easymytrip:latest

jobs:

  build-test:
    name: Compile,Test & Package
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Maven 3.9.12 if not present
        shell: bash
        run: |
          set -e

          MAVEN_VERSION=3.9.12
          MAVEN_DIR=/opt/maven/apache-maven-$MAVEN_VERSION
          MAVEN_BIN=$MAVEN_DIR/bin/mvn

          if [ -x "$MAVEN_BIN" ]; then
            echo "✅ Maven $MAVEN_VERSION already installed"
          else
            echo "⬇️ Installing Maven $MAVEN_VERSION..."
            sudo dnf install -y wget tar

            sudo mkdir -p /opt/maven
            cd /tmp
            wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
            sudo tar -xzf apache-maven-$MAVEN_VERSION-bin.tar.gz -C /opt/maven

            sudo ln -sf $MAVEN_BIN /usr/local/bin/mvn
          fi

          mvn -version

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Package Artifact
        run: mvn package -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar


  docker-build-scan-push:
    name: Docker Build, Scan & Push to ECR
    runs-on: self-hosted
    needs: build-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Verify downloaded artifact
        run: ls -l target

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_LOCAL .
          docker tag $IMAGE_LOCAL $IMAGE_LOCAL_LATEST

          docker tag $IMAGE_LOCAL $IMAGE_DOCKERHUB
          docker tag $IMAGE_LOCAL $IMAGE_DOCKERHUB_LATEST

          docker tag $IMAGE_LOCAL $IMAGE_ECR
          docker tag $IMAGE_LOCAL $IMAGE_ECR_LATEST

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_LOCAL }}
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push to Docker Hub
        run: |
          docker push $IMAGE_DOCKERHUB
          docker push $IMAGE_DOCKERHUB_LATEST

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin 445842764710.dkr.ecr.ap-south-1.amazonaws.com

      - name: Push to Amazon ECR
        run: |
          docker push $IMAGE_ECR
          docker push $IMAGE_ECR_LATEST

      - name: Cleanup Docker Images
        if: always()
        run: |
          docker rmi $IMAGE_LOCAL || true
          docker rmi $IMAGE_LOCAL_LATEST || true
          docker rmi $IMAGE_DOCKERHUB || true
          docker rmi $IMAGE_DOCKERHUB_LATEST || true
          docker rmi $IMAGE_ECR || true
          docker rmi $IMAGE_ECR_LATEST || true
          docker image prune -f || true
